Algoritmo "Atividade02Pagina46"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Giulia Pereira
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
 contadora:inteiro
 soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contadora<- 1
enquanto (contadora<=100) faca
escreva (contadora, " +")
soma <- soma+contadora
contadora<- contadora+1
fimenquanto
escreval ("A soma dos cem números é: ", soma)
Fimalgoritmo