Algoritmo "Atividade04Pagina46"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Mostrar o resultado da potencialização da base 3, do 1 ao 3
// Autor(a)    : Giulia Pereira
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
numero:inteiro
resultado:inteiro
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" 1")
resultado<-1
numero<-3
contadora<-1
enquanto contadora<16 faca
resultado<-resultado*numero
contadora<- contadora+1
escreval (resultado)
fimenquanto

Fimalgoritmo