Algoritmo "Atividade03Pagina46"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Somar os números pares de 1 a 500 e mostrar seu resultado
// Autor(a)    : Giulia Pereira
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
soma: inteiro
contadora:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contadora <-0
enquanto (contadora<=500) faca
escreval (contadora, "+")
soma <- soma+contadora
contadora <- contadora+2
fimenquanto
escreva ("A soma dos números pares de 2 a 500 é: ", soma)

Fimalgoritmo