Algoritmo "semnome"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Digite um número e veja o dia da semana correspondete
// Autor(a)    : Giulia Pereira
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
 dia:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite um número para saber o dia da semana: ")
 leia(dia)
 escolha(dia)
 
 caso 1
 escreval("Domingo")
 caso 2
 escreval("Segunda")
 caso 3
 escreval("Terça")
 caso 4
 escreval("Quarta")
 caso 5
 escreval("Quinta")
 caso 6
 escreval("Sexta")
 caso 7
 escreval("Sabádo")
 outrocaso
 escreval("Não há dia correspondente")
 fimescolha

Fimalgoritmo