Algoritmo "Exercicio20"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois números e colocar em ordem crescente
// Autor(a)    : Giulia Pereira
// Data atual  : 20/03/2023

Var
// Seção de Declarações das variáveis 
valor1:real
valor2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um valor: ")
 leia(valor1)
 escreva("Digite outro valor: ")
 leia(valor2)
 se (valor1>valor2) entao
 escreval (valor2,valor1)
 senao
 escreval (valor1,valor2)
 fimse

Fimalgoritmo