Algoritmo "Multiplicação"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois numeros e exibir o resultado da multiplicação
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
multiplicacao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número")
leia(numero1)
escreva("Digite um número")
leia(numero2)
multiplicacao<-numero1*numero2
escreval("O resultado da multiplicação é :",multiplicacao)
Fimalgoritmo