Algoritmo "Exercicio14"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Pedir um valor e dizer se é maior ou menor que 10
// Autor(a)    : Giulia Pereira
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um valor: ")
leia (valor)
se (valor<10) entao
escreva ("Não é maior que 10")
senao
se (valor=10) entao
escreva ("É igual a 10")
senao
escreva("É maior que 10")
fimse
fimse
Fimalgoritmo