Algoritmo "Exercicio05"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar um número e mostrar o seu Antecessor
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um número: ")
leia(numero1)
antecessor<-numero1-1
escreval("O antecessor deste número é: ",antecessor)
Fimalgoritmo