Algoritmo "Exercicio12"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   :  Converter Fahrenheit para Celsius
// Autor(a)    : Giulia Pereira
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis 
celsius:real
fahrenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite quantos Fº você quer dividir:  ")
leia (fahrenheit)
celsius<-(fahrenheit-32)/1.8
escreva ("A conversão de Fº para Cº é de: ",celsius)
Fimalgoritmo