Algoritmo "Exercicio06.1"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar altura e base do triângulo e exibir o resultado
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
 altura:inteiro
 base:inteiro
 resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite a altura do triângulo: ")
leia(altura)
escreva("Digite a base do triângulo: ")
leia(base)
resultado<-(base*altura)/2
escreval("Resultado: ",resultado,"m²")

Fimalgoritmo