Algoritmo "Exercicio15"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicita um número e diz se é um número positivo ou negativo
// Autor(a)    : Giulia Pereira
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
 numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(numero)
se (numero>=0) entao
escreva("É um número positivo")
senao
escreva("É um número negativo")
 fimse
Fimalgoritmo