Algoritmo "Exercicio06"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   :  Ler as dimensões do retângulo, calcular e exibir a área
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
base:inteiro
altura:inteiro
resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a base:")
leia (base)
escreva("Digite a altura:")
leia(altura)
resultado<-base*altura
escreval("Resultado: ",resultado)
Fimalgoritmo