Algoritmo "Exercicio06.2"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar o raio do circulo e exibir o resultado
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
 raio:inteiro
 resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o raio do circulo:")
leia(raio)
resultado<-(raio*raio)*(3.14)
escreval("Resultado: ",resultado)

Fimalgoritmo