Algoritmo "Soma"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois numeros e exibir o resultado
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número")
leia(numero1)
escreva("Digite um número")
leia(numero2)
soma<-numero1+numero2
escreval("A soma dos valores digitados é :",soma)
Fimalgoritmo