Algoritmo "Divisão"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois numeros e exibir o resultado da divisão
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
divisao:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número")
leia(numero1)
escreva("Digite um número")
leia(numero2)
divisao<-numero1/numero2
escreval("O resultado da divisão é :", divisao)
Fimalgoritmo