Algoritmo "Exercicio19"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar dois valores e mostrar qual o maior entre eles
// Autor(a)    : Giulia Pereira
// Data atual  : 20/03/2023

Var
// Seção de Declarações das variáveis 
valor01:real
valor02:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um valor: ")
leia (valor01)
escreva ("Digite outro valor: ")
 leia (valor02)
 se (valor01>valor02) entao
escreval ("O maior valor é:", valor01)
 senao
escreval ("O maior valor é:", valor02)
fimse

Fimalgoritmo