Algoritmo "Exercicio05.1"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Solicitar um número e mostrar seu sucessor
// Autor(a)    : Giulia Pereira
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Digite um número")
 leia(numero1)
sucessor<-numero1+1
escreval("O sucessor deste número é :", sucessor)
Fimalgoritmo