Algoritmo "MANZANOPAG50C"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Ssntos
// Descrição   : Apresentar todos os números divisíveis por 4 que sejam
//menores que 200
// Autor(a)    : Giulia Pereira
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 contadora<-1
 repita
 se (contadora mod 4 = 0) entao
 escreval (contadora)
 fimse
 contadora<-contadora+1
 ate contadora>200

Fimalgoritmo