Algoritmo "MCDONALD"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Totem do Mc Donald
// Autor(a)    : Giulia Pereira
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
opcao,opcao2,opcao3,opcao4,opcao5,opcao6,opcao7,opcao8,opcao9,opcao10:inteiro
opcao11,opcao12,opcao13,opcao14,opcao15:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("-----------------------------------")
escreval("-----------------------------------")
escreval("****Sistema de Totem MC Donalds****")
escreval("-----------------------------------")
escreval("-----------------------------------")
escreval("")
escreval("")
escreval("SELECIONE A OPÇÃO QUE DESEJA")
escreval("")
escreval("")
escreval("1-Lançamentos")
escreval("2-Brabos do Méqui")
escreval("3-Sanduiches de carne Bovina")
escreval("4-Familia Tasty")
escreval("5-Sanduiches de carne Frango")
escreval("6-Mc Lanche Feliz")
escreval("7-Mc 1000")
escreval("8-Acompanhamentos")
escreval("9-Sobremesas")
escreval("10-Bebidas Frias")
escreval("11-Bebidas Quentes")
escreval("12-Café da Manhã")
escreval("13-Mc Ofertas")
escreval("14-Mc Box")
escreval("15-McCafé")
leia(opcao)
limpatela

escolha opcao

caso 1
escreval("Você selecionou a OPÇÃO 01")
escreval("-------Lançamentos--------")
escreval("")
escreval("")
escreval("01 - McCrispy Chicken Legend")
escreval("02 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Chocolate")
escreval("03 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Morango")
escreval("04 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Caramelo")
leia(opcao 1)
fimescolha
limpatela

caso 2
escreval("Você selecionou a OPÇÃO 02")
escreval("-------Brabos do Méqui--------")
escreval("")
escreval("")
escreval("01 - Brabo Melt Crispy")
escreval("02 - Brabo Bacon Salad")
leia(opcao2)
fimescolha
limpatela

caso 3
escreval("Você selecionou a OPÇÃO 03")
escreval("----Sanduíches de Carne Bovina----")
escreval("")
escreval("")
escreval("01 - Big Mac")
escreval("02 - Duplo Quarterão")
escreval("03 - Quarterão com Queijo")
escreval("04 - McNífico Bacon")
escreval("05 - Duplo Cheddar McMelt")
escreval("06 - Cheddar McMelt")
escreval("07 - Duplo Burger Bacon")
escreval("08 - Duplo Burger com Queijo")
escreval("09 - Tripo Burger")
escreval("10 - McFiesta")
escreval("11 - Cheeseburger")
escreval("12 - Hamburger")
leia(opcao3)
fimescolha
limpatela

caso 4
escreval("Você selecionou a OPÇÃO 04")
escreval("-------Familia Tasty--------")
escreval("")
escreval("")
escreval("01 - Big Tasty")
leia(opcao4)
fimescolha
limpatela

caso 5
Escreval("Você escolheu a opção 05")
Escreval("----Sanduwiches de carne Frango----")
Escreval("")
Escreval("")
Escreval("01 -McCrispy Chicken  Legend")
Escreval("02 - McCrispy Chicken Deluxe")
Escreval("03 - McCrispy  Chicken Melt & Bacon")
Escreval("04 - McChicken Bacon")
Escreval("05 - McChicken")
Escreval("06 - McChicken Jr")
fimescolha
limpatela

caso 6
escreval("Você selecionou a OPÇÃO 06")
escreval("-------McLanche Feliz--------")
escreval("")
escreval("")
escreval("01 - Brabo Melt Crispy")
escreval("02 - Brabo Bacon Salad")
leia(opcao6)
fimescolha
limpatela

caso 7
Escreval("Você escolheu a OPÇÃO 07")
Escreval("------MÉQUI 1000--------")
Escreval("")
Escreval("")
Escreval("01 - Super Mc")
Escreval("02 - McRings Chedder Bacon")
Escreval("03 - Caldo&Freddo Chocolate")
Escreval("04 - Caldo&Freddo Morango")
Escreval("05 - Caldo&Freddo Caramelo")
Escreval("06 - McRings Bacon")
leia(opcao7)
fimescolha
Limpatela

caso 8
   escreval("Você selecionou a OPÇÃO 08")
   escreval("-------Acompanhamentos--------")
   escreval("")
   escreval("")
   escreval("01 - McFritas Cheddar Bacon")
   escreval("02 - McFritas Grande")
   escreval("03 - McFritas Média")
   escreval("04 - McFritas Pequena")
   escreval("05 - McFritas Kids")
   escreval("06 - Chicken McNuggets 6 unidades")
   escreval("07 - Chicken McNuggets 4 unidades")
   escreval("08 - Chicken McNuggets 10 unidades")
   escreval("09 - Molho Agridoce")
   escreval("10 - Molho Barbecue")
   escreval("11 - Molho Ranch")
   escreval("12 - Molho Caipira")
   escreval("13 - Mega McNuggets")
   escreval("14 - Ketchup")
   escreval("15 - Tomatinho")
   escreval("16 - Mega McFritas")
   leia(opcao8)
   fimescolha
   limpatela

caso 09
escreval("Você selecionou a OPÇÃO 09")
escreval("-------Sobremesas--------")
   escreval("")
   escreval("")
   escreval("01 - Casquinha Baunilha")
   escreval("02 - Casquinha Chocolate")
   escreval("03 - Casquinha Mista")
   escreval("04 - Sundae Morango")
   escreval("05 - Sundae Chocolate")
   escreval("06 - Sundae Caramelo")
   escreval("07 - Top Sundae Morango")
   escreval("08 - Top Sundae Chocolate")
   escreval("09 - McColosso Chocolate")
   escreval("10 - McColosso Caramelo")
   escreval("11 - Petit Suisse Sabor Morango")
   escreval("12 - Torta de Maçã")
   escreval("13 - Torta de Banana")
   escreval("14 - McShake Morango")
   escreval("15 - McShake Ovomaltine")
   escreval("16 - McShake Kopenhagen")
   escreval("17 - McFlurry Ovomaltine®")
   escreval("18 - McFlurry Prestígio Chocolate")
   escreval("19 - McFlurry Prestígio Morango")
   escreval("20 - McFlurry Prestígio Caramelo")
   escreval("21 - McFlurry Ovomaltine chocolate")
   escreval("22 - McFlurry Ovomaltine Morango")
   escreval("23 - McFlurry Ovomaltine Caramelo")
   escreval("24 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Chocolate")
   escreval("25 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Morango")
   escreval("26 - McFlurry Trufa Lingua de Gato DUO Kopenhagen Caramelo")
   leia(opcao9)
   fimescolha
   limpatela

caso 10
Escreval("Você escolheu a OPÇÃO 10")
Escreval("------Bebidas Frias-----")
Escreval("")
Escreval("")
Escreval("01 - Coca-Cola 500ML")
Escreval("02 - Coca-Cola 700ML")
Escreval("03 - Coca-Cola Zero 300ML")
Escreval("04 - Coca-Cola Zero 500ML")
Escreval("05 - Coca-Cola Zero 700ML")
Escreval("06 - Fanta Laranja 300ML")
Escreval("07 - Fanta Guaraná 300ML")
Escreval("08 - Fanta Guaraná 500ML")
Escreval("09 - Fanta Guaraná 700ML")
Escreval("10 - Del Valle Laranja 300ML")
Escreval("11 - Del Valle Lranja 500ML")
Escreval("12 - Del Valle Laranja 700ML")
Escreval("13 - Del Valle Uva 300ML")
Escreval("14 - Del Valle Uva 500ML")
Escreval("15 - Del Valle Uva 700ML")
Escreval("16 - Água Mineral")
Escreval("17 - Del Valle 100% Uva (McLanche Feliz)")
leia(opcao10)
fimescolha
Limpatela

caso 11
Escreval("Você escolheu a opção 11")
Escreval("------------Café da Manhã------------")
Escreval("")
Escreval("")
Escreval("01 - Capuccino 200ml")
Escreval("02 - Capuccino 300ml")
Escreval("03 - Café com Leite 200ml")
Escreval("04 - Café com Leite 300ml")
Escreval("05 - Café Premium 100ml")
Escreval("06 - Café Premium 200ml")
Escreval("07 - Café Premium 300ml")
Escreval("08 - Chocolate Quente 200ml")
Escreval("09 - Chocolate Quente 300ml")
Escreval("10 - Queijo Quente")
Escreval("11 - Croissant de Presunto e Queijo")
Escreval("12 - Pão de Queijo")
leia(opcao11)
fimescolha
Limpatela

caso 12
escreval("Você selecionou a OPÇÃO 12")
escreval("-------Bebidas Quentes--------")
escreval("")
escreval("")
escreval("01 - Café Premium 100ml")
escreval("02 - Café Premium 200ml")
escreval("03 - Café Premium 300ml")
escreval("04 - Café com Leite 200ml")
escreval("05 - Café com Leite 300ml")
escreval("06 - Capuccino 200ml")
escreval("07 - Capuccino 300ml")
escreval("08 - Chocolate Quente 200ml")
escreval("09 - Chocolate Quente 300ml")
leia(opcao12)
fimescolha
limpatela

caso 13
escreval("Você selecionou a OPÇÃO 13")
escreval("-------McOferta--------")
escreval("")
escreval("")
escreval("01 - Big Mac")
escreval("02 - Quarterão com queijo")
escreval("03 - Cheddar McMelt")
leia(opcao13)
fimescolha
limpatela

caso 14
escreval("Você selecionou a OPÇÃO 14")
escreval("--------Méqui Box---------")
escreval("")
escreval("")
escreval("01 - Family Box para 2")
escreval("02 - Family Box para 3")
escreval("03 - Méqui Box Clássico para 3")
escreval("04 - Méqui Box Clássico para 4")
leia(opcao14)
fimescolha
limpatela

caso 15
escreval("Você selecionou a OPÇÃO 15")
escreval("----------McCafé----------")
escreval("")
escreval("")
escreval("01 - Cookie de Baunilha com Gotas de Chocolate")
escreval("02 - Pão de Queijo")
escreval("03 - Croissant de Presunto e Queijo")
escreval("04 - Mini Pão de Queijo")
escreval("05 - Quiche de Palmito")
escreval("06 - Tartelete de Cheesecake com Cobertura de Morango")
escreval("07 - Muffin de Blueberry")
escreval("08 - Bolo de laranja")
leia(opcao15)
fimescolha
limpatela


Fimalgoritmo