Algoritmo "semnome"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Digite um número e veja o mês correspondente
// Autor(a)    : Giulia Pereira
// Data atual  : 23/03/2023
Var
// Seção de Declarações das variáveis 
meses:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número e saiba o mês: ")
leia(meses)
escolha meses

caso 1
escreval("Janeiro")
caso 2
escreval("Feveiro")
caso 3
escreval("Março")
caso 4
escreval("Abril")
caso 5
escreval("Maio")
caso 6
escreval("Junho")
caso 7
escreval("Julho")
caso 8
escreval("Agosto")
caso 9
escreval("Setembro")
caso 10
escreval("Outubro")
caso 11
escreval("Novembro")
caso 12
escreval("Dezembro")
outrocaso
escreval("Não há mês correspondente")
fimescolha

Fimalgoritmo